version: "2.4"

services:
  
  progrid:
    image: selenium/hub:3.141.59
    container_name: selenium_hub
    ports: 
      [4444:4444]
  
  nodechrome:
        image: selenium/node-chrome:3.141.59
        scale: 4
        privileged: true
        depends_on:
          - progrid
        ports:
          - 5900
        environment:
          - HUB_PORT_4444_TCP_ADDR=progrid
          - HUB_PORT_4444_TCP_PORT=4444